### ISSUE TITLE
Reduce font size / size of post for larger screens

### ISSUE THREAD

**Issue by infosec-au** [kathyqian/crisp-ghost-theme#22]
On larger screens when browsing through a blog post, the font size is quite large and since the text spans all the way across the larger screen - it's really hard to read the post with a good flow.

Example:

http://i.imgur.com/PlCVmrg.png

This is probably opinionated, but perhaps limiting the width of the blog post content would be a solution?

**Comment by danieltech** [comment]
Hi,

could someone advice me how to make the text not getting smaller when there are break points? from my point of view, the size is very small if you want to read on mobile devices.

by the way, excellent theme!

regards

**Comment by kathyqian** [comment]
@danieltech You can add css under the "/* Tiny Screens */" section to explicitly set a font size for smaller screens.

**Comment by kathyqian** [comment]
@ianbannerman Adding your suggestion to 0.5.0.
