### ISSUE TITLE
File Structure Within Repository

### ISSUE THREAD

**Issue by pyrmont** [kathyqian/crisp-ghost-theme#33]
Is there a particular reason to have the theme files in a separate `crisp` subdirectory?

I really love Crisp and am interested in using it as a submodule within an existing repository. I could get things to work as a submodule if the files were all in the root of the repo but as they're not, I can't see how I can do it at the moment (if I checked out this project I'd end up with a directory structure like `content/themes/crisp/crisp/` instead of `content/themes/crisp/`).

The [Casper theme](https://github.com/TryGhost/Casper/tree/e669b29895866ce652dc674cca1ea5c509da3716) in structured with the `README` in the root of the 'theme proper' as it were. Could Crisp do the same?

**Comment by kathyqian** [comment]
Great idea that has been proposed multiple times. Clearly the original file structure was a poor choice, so it will be changed in the next push.
