### ISSUE TITLE
about tag  

### ISSUE THREAD

**Issue by cbccool** [kathyqian/crisp-ghost-theme#36]
excuse me , i like this theme very much ,thank you. but i hava a question , that is   how can i add tags when i create  a new post ?

**Comment by adolphenom** [comment]
That is not theme-related but Ghost-related. You should check the documentation: http://www.ghostforbeginners.com/how-to-categorize-ghost-blog-posts-with-tags/

Cheers!

**Comment by cbccool** [comment]
oh!!!!!!!!! I find it!!!
Thank you !!!
