### ISSUE TITLE
Highlight.js and the theme

### ISSUE THREAD

**Issue by adolphenom** [kathyqian/crisp-ghost-theme#37]
Hi!

Thank you for the update to 0.5.0 and the Ghost 0.5.x support :) I'm happy to see that this project is still up!

But, after I cloned and chose the new theme, I noticed that "code" tag (\`adada\` and the 4 spaces) have the font bigger than before, and I couldn't figure out how to put a lower font size.

Also (and I hope this is a Highlight.js problem) if I change the theme, only the 4 spaces indented code change its theme but not the \`asas\` stuff.

Thank you for your help!

**Comment by kathyqian** [comment]
You can change the font size in assets/styles/crisp.css under code {} (line 111)
